[package]
name = "flag2"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.98"
chrono = "0.4.40"
crossterm = { version = "0.29.0", features = ["event-stream"] }
futures = "0.3.31"
rand = "0.9.1"
tokio = { version = "1.44.2", features = ["full"] }
