[package]
name = "slot-machine-procmacro"
version = "0.1.0"
edition = "2024"

[lib]
proc-macro = true

[dependencies]
syn = {version = "1.0", features = ["full"]}
quote = "1.0"
proc-macro2 = "1.0"
slot-machine-crypto = { path = "../slot-machine-crypto", features = ["encrypt"] }
rand = "0.9.0"
