[package]
name = "slot-machine-crypto"
version = "0.1.0"
edition = "2021"
license = "MIT OR Apache-2.0"
description = "Cryptographic functionality for the Wonderlight Slot Machine"
authors = ["zer0x64"]

[dependencies]

[features]
default = []
encrypt = []
decrypt = []
